### ISSUE TITLE
404 when navigating directly to pages

### ISSUE THREAD

**Issue by vyrak** [recharts/recharts.org#56]
Navigating to http://recharts.org/en-US/ directly gives a 404 or for, where as going to http://recharts.org/ redirects me to http://recharts.org/en-US/ and loads fine.

This problem occurs for any other routes under http://recharts.org/en-US/ as well. It makes bookmarking and sharing links difficult.

**Comment by breadadams** [comment]
As described in https://github.com/recharts/recharts/issues/1279 & https://github.com/recharts/recharts/issues/1280

**Comment by augustobmoura** [comment]
It's happening again, it is even more evident because Brave Browser actually shows a popup when any website responds with a 404
![image](https://user-images.githubusercontent.com/5845160/76185242-8e213980-61ad-11ea-9495-12ce591b8047.png)

The problem is with the backend, it's probably just responding the index page to any resource not found to make the virtual router work correctly, it should also respond with 200 status
